[project]
name = "hopscotch"
version = "0.1.0"
description = "Hopscotch data analysis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
    "scipy>=1.15.2",
    "tqdm>=4.67.1",
]
